version: "3.7"

services:
  database:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=apipersonal
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  backend:
    build: .
    restart: always
    ports:
      - 3300:3300
      - 9229:9229
    volumes:
      - . :/usr/app
    network_mode: host
    depends_on:
      - database
volumes:
  pgdata:
    driver: local
